### PR TITLE
Fix vanilla formation selection saving

### LINKED ISSUE #11: Fix vanilla formation selection saving
# Description

- Vanilla saving of formation choices for units is broken
- Permission has been granted to utilise logic from this mod https://www.nexusmods.com/mountandblade2bannerlord/mods/626

# Context

- Within scope of this mod to fix it
- Improves UX of party management

### PR DESCRIPTION
**Pull request by MLNW**
**When merged this pull request will:**

- Resolve #11 
- Add run configurations that use the launcher instead of directly launching the game

### CODE REVIEW

File: Extension/YapoSubModule.cs [hunk 1]
```diff
@@ -25,25 +27,48 @@ protected override void OnSubModuleLoad()
                 FileDatabase.Initialise(Strings.MODULE_FOLDER_NAME);
                 Settings settings = FileDatabase.Get<Settings>(Settings.InstanceId) ?? new Settings();
                 SettingsDatabase.RegisterSettings(settings);
-                
+
                 UIExtender.Register();
                 new Harmony("YAPO").PatchAll();
-            } catch (Exception exception)
+            }
+            catch (Exception e)
```
Comment (tbeswick96) [inline Extension/YapoSubModule.cs]: Why change this to `e`?
`Exception` is clearer. Personally prefer variable names that aren't shortened or abbreviated (except for LINQ predicates)

File: Extension/Fixes/Formations/FixedFormationsBehaviour.cs [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+    {
+        public static readonly FixedFormationsBehaviour Instance = new FixedFormationsBehaviour();
+
+        public Dictionary<BasicCharacterObject, FormationClass> FormationClasses;
+
+        public bool GameStarted { get; set; }
+
+        public override void RegisterEvents()
+        {
+            // Nothing to register
```
Comment (tbeswick96) [inline Extension/Fixes/Formations/FixedFormationsBehaviour.cs]: Just empty contrsuctor `RegisterEvents() { }`

File: Extension/Fixes/Formations/FixedFormationsSaveableTypeDefiner.cs [hunk 3]
```diff
@@ -0,0 +1,24 @@
...
+using TaleWorlds.Core;
+using TaleWorlds.SaveSystem;
+
+namespace YAPO.Fixes.Formations
+{
+    public class FixedFormationsSaveableTypeDefiner : SaveableTypeDefiner
+    {
+        public FixedFormationsSaveableTypeDefiner() : base(13537200)
+        {
+            // Nothing to do
```
Comment (tbeswick96) [inline Extension/Fixes/Formations/FixedFormationsSaveableTypeDefiner.cs]: Just empty constructor `base(13537200) { }`

**Review by tbeswick96 — CHANGES_REQUESTED** [review]
All looks fine, seems like a simple implementation so that's good.
Some formatting I'm not a fan of which I'll fix in a commit to master with a full .DotSettings file included so hopefully going forward it won't be as much of a problem

File: Extension/YapoSubModule.cs (hunk 1 above)
Comment (MLNW) [reply Extension/YapoSubModule.cs]: I usually agree with this but in the case of exceptions in a try-catch block I usually shorten them since lines tend to grow long with exception messages and all.

I'll revert it.

**Comment by MLNW** [comment]
Still have to test it on the 1.2.0 beta branch

**Comment by MLNW** [comment]
As it stands we need to implement this differently for 1.1.1 and 1.2.0 since there was a change relating to the `Campaign` class that is used to figure out when everything has been loaded and the game actually starts.

Question now is do we support both versions or only one? Since this feature isn't really core to our mission it may be best to simply implement it for the newer version and have it go live as soon as 1.2.0 isn't beta anymore.

**Comment by tbeswick96** [comment]
How tricky is it to have it for both? Can it be resolved through reflection based on version to avoid having to explicitly specify the thing needed from `Campaign`?

**Comment by MLNW** [comment]
> How tricky is it to have it for both? Can it be resolved through reflection based on version to avoid having to explicitly specify the thing needed from `Campaign`?

We would need to patch different methods on `TaleWorlds.CampaignSystem.Campaing`:
- `OnSessionInitialized --> 1.1.1`
- `OnSessionStart        --> 1.2.0`

From a quick look they do the same thing but for what ever reason they decided to rename the method.

For 1.2.0 there was also another patch added for `TaleWorlds.Core.BasicCharacterObject.DefaultFormationGroup`. Sounds like it was added for 1.2.0.

I haven't worked with reflection in C# so I'm not sure if it's possible. But it does sound feasible. `YAPO.Fixes.Formations.Patches.CampaignPatches` would need to take into account the current version and patch different methods depending on it. That should be possible with Harmonys `TargetMethod` syntax.

For the `DefaultFormationGroup` I'm not sure. It may be problematic if it was only added for 1.2.0 but there is probably a way similar to the one above.

EDIT: I found this which I will try to check for the version: https://stackoverflow.com/a/12528418

**Review by tbeswick96 — APPROVED** [review]
Lgtm
